variable vpc_id {}
variable domains {}
variable ami_id {}
variable private_subnets {}
variable public_subnets {}
variable use_spot {}
variable "create_ssh_key" {}
variable "db_password" {}
variable "db_name" {}
variable "db_user" {}
variable "db_endpoint" {}
variable "email" {}
variable "instance_type" {}
variable "efs_dns" {}
variable "dry_run" {}
